name: ci

on:
  schedule:
  - cron: "0 0 * * *"
  push:

jobs:
  docker:
    strategy:
      matrix:
        version: [8.3, 8.4]
        variant: [debug, release]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: iantorres/php:${{ matrix.version }}-${{ matrix.variant }}
          build-args: |
            PHP_VERSION=${{ matrix.version }}
            PHP_VARIANT=${{ matrix.variant }}
